version: "3.9"

services:
  php-app:
    build:
      context: ./app
      dockerfile: Dockerfile
    image: marketplace-php-app
    container_name: marketplace-php-app
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8
    container_name: marketplace-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: marketplace
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
#      - ./my.cnf:/etc/mysql/conf.d/my.cnf

volumes:
  db_data:
